# Home Assistant Configuration
HASS_URL="http://homeassistant:8123"
HASS_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzZTAyOTFlM2RkMmE0NmMwYTVjNTg4YTBmMzk5ZDEyNCIsImlhdCI6MTczNTA3NTczMiwiZXhwIjoyMDUwNDM1NzMyfQ.-KTx4WZCub01wqSSPlEp8gF_hqjRbuYpCgv2-Fk5h-c"
HASS_ENTITY="input_number.usage_limit" 